<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>sems-background</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SEMS.Infrastructure\SEMS.Infrastructure.csproj" />
    <ProjectReference Include="..\SEMS.Application\SEMS.Application.csproj" />
    <ProjectReference Include="..\SEMS.Core\SEMS.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
  </ItemGroup>
</Project>

